### ISSUE TITLE
Possible bug in generate_realizations_from_gcmt.py

### ISSUE THREAD

**Issue by sungeunbae** [ucgmsim/Pre-processing#231]
From Sarah,

```
(python3_maui) sjn87@maui02: /nesi/nobackup/nesi00213/RunFolder/sjn87/NZ$ python $gmsim/Pre-processing/srf_generation/source_parameter_generation/generate_realisations_from_gcmt.py list_all GeoNet_CMT_NZ.csv 1 --version sjn_realisations_v905 -a results.csv --vs30_median geoNet_stats+2022-06-14.vs30 --vs30_sigma geoNet_stats+2022-06-14.vs30_stddev --source_parameter rdistance_sigma NZ.rdistance_stddev --source_parameter depth_sigma NZ.depth_stddev
<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/virt_envs/python3_maui/lib/python3.9/site-packages/pandas/core/indexing.py", line 1618, in _get_list_axis
    return self.obj._take_with_is_copy(key, axis=axis)
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/virt_envs/python3_maui/lib/python3.9/site-packages/pandas/core/series.py", line 971, in _take_with_is_copy
    return self.take(indices=indices, axis=axis)
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/virt_envs/python3_maui/lib/python3.9/site-packages/pandas/core/series.py", line 956, in take
    new_index = self.index.take(indices)
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/virt_envs/python3_maui/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 1090, in take
    taken = algos.take(
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/virt_envs/python3_maui/lib/python3.9/site-packages/pandas/core/algorithms.py", line 1257, in take
    result = arr.take(indices, axis=axis)
IndexError: index 34 is out of bounds for axis 0 with size 34

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nesi/project/nesi00213/Environments/sjn872022/Pre-processing/srf_generation/source_parameter_generation/generate_realisations_from_gcmt.py", line 316, in <module>
    main()
  File "/nesi/project/nesi00213/Environments/sjn872022/Pre-processing/srf_generation/source_parameter_generation/generate_realisations_from_gcmt.py", line 264, in main
    additional_source_parameters = get_additional_source_parameters(
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/Pre-processing/srf_generation/source_parameter_generation/gcmt_to_realisation.py", line 259, in get_additional_source_parameters
    "vs": get_depth_property(gcmt_data["depth"], vel_mod_1d_layers, "vs"),
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/Pre-processing/srf_generation/source_parameter_generation/common.py", line 138, in get_depth_property
    return np.asarray(vel_mod_1d_layers[property_name].iloc[binned_depths])
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/virt_envs/python3_maui/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/virt_envs/python3_maui/lib/python3.9/site-packages/pandas/core/indexing.py", line 1647, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/scale_wlg_persistent/filesets/project/nesi00213/Environments/sjn872022/virt_envs/python3_maui/lib/python3.9/site-packages/pandas/core/indexing.py", line 1621, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds") from err
IndexError: positional indexers are out-of-bounds

```

**Comment by sungeunbae** [comment]
There was invalid entries in the GCMT file, and the Pre-process code Sarah used were outdated. All resolved.
